/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as DevTestRouteImport } from "./routes/dev.test"
import { Route as AppCoursesIndexRouteImport } from "./routes/_app/courses.index"
import { Route as AppAssetsIndexRouteImport } from "./routes/_app/assets.index"
import { Route as AppCoursesNewRouteImport } from "./routes/_app/courses.new"
import { Route as AppAssetsNewRouteImport } from "./routes/_app/assets.new"
import { Route as AppCoursesIdIndexRouteImport } from "./routes/_app/courses.$id.index"
import { Route as AppCoursesIdEditRouteImport } from "./routes/_app/courses.$id.edit"

const AppIndexRoute = AppIndexRouteImport.update({
  id: "/_app/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DevTestRoute = DevTestRouteImport.update({
  id: "/dev/test",
  path: "/dev/test",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: "/_app/courses/",
  path: "/courses/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: "/_app/assets/",
  path: "/assets/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesNewRoute = AppCoursesNewRouteImport.update({
  id: "/_app/courses/new",
  path: "/courses/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsNewRoute = AppAssetsNewRouteImport.update({
  id: "/_app/assets/new",
  path: "/assets/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIdIndexRoute = AppCoursesIdIndexRouteImport.update({
  id: "/_app/courses/$id/",
  path: "/courses/$id/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIdEditRoute = AppCoursesIdEditRouteImport.update({
  id: "/_app/courses/$id/edit",
  path: "/courses/$id/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/dev/test": typeof DevTestRoute
  "/": typeof AppIndexRoute
  "/assets/new": typeof AppAssetsNewRoute
  "/courses/new": typeof AppCoursesNewRoute
  "/assets": typeof AppAssetsIndexRoute
  "/courses": typeof AppCoursesIndexRoute
  "/courses/$id/edit": typeof AppCoursesIdEditRoute
  "/courses/$id": typeof AppCoursesIdIndexRoute
}
export interface FileRoutesByTo {
  "/dev/test": typeof DevTestRoute
  "/": typeof AppIndexRoute
  "/assets/new": typeof AppAssetsNewRoute
  "/courses/new": typeof AppCoursesNewRoute
  "/assets": typeof AppAssetsIndexRoute
  "/courses": typeof AppCoursesIndexRoute
  "/courses/$id/edit": typeof AppCoursesIdEditRoute
  "/courses/$id": typeof AppCoursesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/dev/test": typeof DevTestRoute
  "/_app/": typeof AppIndexRoute
  "/_app/assets/new": typeof AppAssetsNewRoute
  "/_app/courses/new": typeof AppCoursesNewRoute
  "/_app/assets/": typeof AppAssetsIndexRoute
  "/_app/courses/": typeof AppCoursesIndexRoute
  "/_app/courses/$id/edit": typeof AppCoursesIdEditRoute
  "/_app/courses/$id/": typeof AppCoursesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/dev/test"
    | "/"
    | "/assets/new"
    | "/courses/new"
    | "/assets"
    | "/courses"
    | "/courses/$id/edit"
    | "/courses/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/dev/test"
    | "/"
    | "/assets/new"
    | "/courses/new"
    | "/assets"
    | "/courses"
    | "/courses/$id/edit"
    | "/courses/$id"
  id:
    | "__root__"
    | "/dev/test"
    | "/_app/"
    | "/_app/assets/new"
    | "/_app/courses/new"
    | "/_app/assets/"
    | "/_app/courses/"
    | "/_app/courses/$id/edit"
    | "/_app/courses/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DevTestRoute: typeof DevTestRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsNewRoute: typeof AppAssetsNewRoute
  AppCoursesNewRoute: typeof AppCoursesNewRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesIdEditRoute: typeof AppCoursesIdEditRoute
  AppCoursesIdIndexRoute: typeof AppCoursesIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dev/test": {
      id: "/dev/test"
      path: "/dev/test"
      fullPath: "/dev/test"
      preLoaderRoute: typeof DevTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/": {
      id: "/_app/courses/"
      path: "/courses"
      fullPath: "/courses"
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/assets/": {
      id: "/_app/assets/"
      path: "/assets"
      fullPath: "/assets"
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/new": {
      id: "/_app/courses/new"
      path: "/courses/new"
      fullPath: "/courses/new"
      preLoaderRoute: typeof AppCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/assets/new": {
      id: "/_app/assets/new"
      path: "/assets/new"
      fullPath: "/assets/new"
      preLoaderRoute: typeof AppAssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$id/": {
      id: "/_app/courses/$id/"
      path: "/courses/$id"
      fullPath: "/courses/$id"
      preLoaderRoute: typeof AppCoursesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$id/edit": {
      id: "/_app/courses/$id/edit"
      path: "/courses/$id/edit"
      fullPath: "/courses/$id/edit"
      preLoaderRoute: typeof AppCoursesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DevTestRoute: DevTestRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsNewRoute: AppAssetsNewRoute,
  AppCoursesNewRoute: AppCoursesNewRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesIdEditRoute: AppCoursesIdEditRoute,
  AppCoursesIdIndexRoute: AppCoursesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
