/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as DevTestRouteImport } from "./routes/dev.test"
import { Route as AppCoursesIndexRouteImport } from "./routes/_app/courses/index"
import { Route as AppAssetsIndexRouteImport } from "./routes/_app/assets/index"
import { Route as AppCoursesNewRouteImport } from "./routes/_app/courses/new"
import { Route as AppAssetsNewRouteImport } from "./routes/_app/assets/new"
import { Route as AppCoursesCourseIdIndexRouteImport } from "./routes/_app/courses/$courseId/index"
import { Route as AppCoursesCourseIdEditRouteImport } from "./routes/_app/courses/$courseId/edit"
import { Route as AppCoursesCourseIdModulesIndexRouteImport } from "./routes/_app/courses/$courseId/modules/index"
import { Route as AppCoursesCourseIdModulesNewRouteImport } from "./routes/_app/courses/$courseId/modules/new"
import { Route as AppCoursesCourseIdModulesModuleIdIndexRouteImport } from "./routes/_app/courses/$courseId/modules/$moduleId/index"
import { Route as AppCoursesCourseIdModulesModuleIdEditRouteImport } from "./routes/_app/courses/$courseId/modules/$moduleId/edit"

const AppIndexRoute = AppIndexRouteImport.update({
  id: "/_app/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DevTestRoute = DevTestRouteImport.update({
  id: "/dev/test",
  path: "/dev/test",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: "/_app/courses/",
  path: "/courses/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: "/_app/assets/",
  path: "/assets/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesNewRoute = AppCoursesNewRouteImport.update({
  id: "/_app/courses/new",
  path: "/courses/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsNewRoute = AppAssetsNewRouteImport.update({
  id: "/_app/assets/new",
  path: "/assets/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: "/_app/courses/$courseId/",
  path: "/courses/$courseId/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesCourseIdEditRoute = AppCoursesCourseIdEditRouteImport.update({
  id: "/_app/courses/$courseId/edit",
  path: "/courses/$courseId/edit",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesCourseIdModulesIndexRoute =
  AppCoursesCourseIdModulesIndexRouteImport.update({
    id: "/_app/courses/$courseId/modules/",
    path: "/courses/$courseId/modules/",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCoursesCourseIdModulesNewRoute =
  AppCoursesCourseIdModulesNewRouteImport.update({
    id: "/_app/courses/$courseId/modules/new",
    path: "/courses/$courseId/modules/new",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCoursesCourseIdModulesModuleIdIndexRoute =
  AppCoursesCourseIdModulesModuleIdIndexRouteImport.update({
    id: "/_app/courses/$courseId/modules/$moduleId/",
    path: "/courses/$courseId/modules/$moduleId/",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCoursesCourseIdModulesModuleIdEditRoute =
  AppCoursesCourseIdModulesModuleIdEditRouteImport.update({
    id: "/_app/courses/$courseId/modules/$moduleId/edit",
    path: "/courses/$courseId/modules/$moduleId/edit",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/dev/test": typeof DevTestRoute
  "/": typeof AppIndexRoute
  "/assets/new": typeof AppAssetsNewRoute
  "/courses/new": typeof AppCoursesNewRoute
  "/assets": typeof AppAssetsIndexRoute
  "/courses": typeof AppCoursesIndexRoute
  "/courses/$courseId/edit": typeof AppCoursesCourseIdEditRoute
  "/courses/$courseId": typeof AppCoursesCourseIdIndexRoute
  "/courses/$courseId/modules/new": typeof AppCoursesCourseIdModulesNewRoute
  "/courses/$courseId/modules": typeof AppCoursesCourseIdModulesIndexRoute
  "/courses/$courseId/modules/$moduleId/edit": typeof AppCoursesCourseIdModulesModuleIdEditRoute
  "/courses/$courseId/modules/$moduleId": typeof AppCoursesCourseIdModulesModuleIdIndexRoute
}
export interface FileRoutesByTo {
  "/dev/test": typeof DevTestRoute
  "/": typeof AppIndexRoute
  "/assets/new": typeof AppAssetsNewRoute
  "/courses/new": typeof AppCoursesNewRoute
  "/assets": typeof AppAssetsIndexRoute
  "/courses": typeof AppCoursesIndexRoute
  "/courses/$courseId/edit": typeof AppCoursesCourseIdEditRoute
  "/courses/$courseId": typeof AppCoursesCourseIdIndexRoute
  "/courses/$courseId/modules/new": typeof AppCoursesCourseIdModulesNewRoute
  "/courses/$courseId/modules": typeof AppCoursesCourseIdModulesIndexRoute
  "/courses/$courseId/modules/$moduleId/edit": typeof AppCoursesCourseIdModulesModuleIdEditRoute
  "/courses/$courseId/modules/$moduleId": typeof AppCoursesCourseIdModulesModuleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/dev/test": typeof DevTestRoute
  "/_app/": typeof AppIndexRoute
  "/_app/assets/new": typeof AppAssetsNewRoute
  "/_app/courses/new": typeof AppCoursesNewRoute
  "/_app/assets/": typeof AppAssetsIndexRoute
  "/_app/courses/": typeof AppCoursesIndexRoute
  "/_app/courses/$courseId/edit": typeof AppCoursesCourseIdEditRoute
  "/_app/courses/$courseId/": typeof AppCoursesCourseIdIndexRoute
  "/_app/courses/$courseId/modules/new": typeof AppCoursesCourseIdModulesNewRoute
  "/_app/courses/$courseId/modules/": typeof AppCoursesCourseIdModulesIndexRoute
  "/_app/courses/$courseId/modules/$moduleId/edit": typeof AppCoursesCourseIdModulesModuleIdEditRoute
  "/_app/courses/$courseId/modules/$moduleId/": typeof AppCoursesCourseIdModulesModuleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/dev/test"
    | "/"
    | "/assets/new"
    | "/courses/new"
    | "/assets"
    | "/courses"
    | "/courses/$courseId/edit"
    | "/courses/$courseId"
    | "/courses/$courseId/modules/new"
    | "/courses/$courseId/modules"
    | "/courses/$courseId/modules/$moduleId/edit"
    | "/courses/$courseId/modules/$moduleId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/dev/test"
    | "/"
    | "/assets/new"
    | "/courses/new"
    | "/assets"
    | "/courses"
    | "/courses/$courseId/edit"
    | "/courses/$courseId"
    | "/courses/$courseId/modules/new"
    | "/courses/$courseId/modules"
    | "/courses/$courseId/modules/$moduleId/edit"
    | "/courses/$courseId/modules/$moduleId"
  id:
    | "__root__"
    | "/dev/test"
    | "/_app/"
    | "/_app/assets/new"
    | "/_app/courses/new"
    | "/_app/assets/"
    | "/_app/courses/"
    | "/_app/courses/$courseId/edit"
    | "/_app/courses/$courseId/"
    | "/_app/courses/$courseId/modules/new"
    | "/_app/courses/$courseId/modules/"
    | "/_app/courses/$courseId/modules/$moduleId/edit"
    | "/_app/courses/$courseId/modules/$moduleId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DevTestRoute: typeof DevTestRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsNewRoute: typeof AppAssetsNewRoute
  AppCoursesNewRoute: typeof AppCoursesNewRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesCourseIdEditRoute: typeof AppCoursesCourseIdEditRoute
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
  AppCoursesCourseIdModulesNewRoute: typeof AppCoursesCourseIdModulesNewRoute
  AppCoursesCourseIdModulesIndexRoute: typeof AppCoursesCourseIdModulesIndexRoute
  AppCoursesCourseIdModulesModuleIdEditRoute: typeof AppCoursesCourseIdModulesModuleIdEditRoute
  AppCoursesCourseIdModulesModuleIdIndexRoute: typeof AppCoursesCourseIdModulesModuleIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dev/test": {
      id: "/dev/test"
      path: "/dev/test"
      fullPath: "/dev/test"
      preLoaderRoute: typeof DevTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/": {
      id: "/_app/courses/"
      path: "/courses"
      fullPath: "/courses"
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/assets/": {
      id: "/_app/assets/"
      path: "/assets"
      fullPath: "/assets"
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/new": {
      id: "/_app/courses/new"
      path: "/courses/new"
      fullPath: "/courses/new"
      preLoaderRoute: typeof AppCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/assets/new": {
      id: "/_app/assets/new"
      path: "/assets/new"
      fullPath: "/assets/new"
      preLoaderRoute: typeof AppAssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$courseId/": {
      id: "/_app/courses/$courseId/"
      path: "/courses/$courseId"
      fullPath: "/courses/$courseId"
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$courseId/edit": {
      id: "/_app/courses/$courseId/edit"
      path: "/courses/$courseId/edit"
      fullPath: "/courses/$courseId/edit"
      preLoaderRoute: typeof AppCoursesCourseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$courseId/modules/": {
      id: "/_app/courses/$courseId/modules/"
      path: "/courses/$courseId/modules"
      fullPath: "/courses/$courseId/modules"
      preLoaderRoute: typeof AppCoursesCourseIdModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$courseId/modules/new": {
      id: "/_app/courses/$courseId/modules/new"
      path: "/courses/$courseId/modules/new"
      fullPath: "/courses/$courseId/modules/new"
      preLoaderRoute: typeof AppCoursesCourseIdModulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$courseId/modules/$moduleId/": {
      id: "/_app/courses/$courseId/modules/$moduleId/"
      path: "/courses/$courseId/modules/$moduleId"
      fullPath: "/courses/$courseId/modules/$moduleId"
      preLoaderRoute: typeof AppCoursesCourseIdModulesModuleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$courseId/modules/$moduleId/edit": {
      id: "/_app/courses/$courseId/modules/$moduleId/edit"
      path: "/courses/$courseId/modules/$moduleId/edit"
      fullPath: "/courses/$courseId/modules/$moduleId/edit"
      preLoaderRoute: typeof AppCoursesCourseIdModulesModuleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DevTestRoute: DevTestRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsNewRoute: AppAssetsNewRoute,
  AppCoursesNewRoute: AppCoursesNewRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesCourseIdEditRoute: AppCoursesCourseIdEditRoute,
  AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  AppCoursesCourseIdModulesNewRoute: AppCoursesCourseIdModulesNewRoute,
  AppCoursesCourseIdModulesIndexRoute: AppCoursesCourseIdModulesIndexRoute,
  AppCoursesCourseIdModulesModuleIdEditRoute:
    AppCoursesCourseIdModulesModuleIdEditRoute,
  AppCoursesCourseIdModulesModuleIdIndexRoute:
    AppCoursesCourseIdModulesModuleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
